### ISSUE TITLE
provide a canonical API to get the OpenShift token

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/ngx-login-client#22]
this relates to #20 really.

* when using vanilla OAuth then there's only one token (e.g. fabric8-runtime-console). 
* when using almighty back end  (fabric8-ui) we'll need an API to fetch the openshift token via OSO (using the current keycloak token to fetch it).

Ideally we'd have a single API we can use in downstream apps (e.g.  fabric8-runtime-console and fabric8-ui) to get the openshift token.

Mostly its just a case of adding an API; reusing OAuth token or for almighty talking to almighty/keycloak to the the OSO token

**Comment by dgutride** [comment]
Fixed via #23 -  closing
