### ISSUE TITLE
Cannot link accounts due to AuthenticationService broadcasting authenticationError

### ISSUE THREAD

**Issue by dlabrecq** [fabric8-ui/ngx-login-client#55]
AuthenticationService.createFederatedToken recently started broadcasting an authenticationError when keycloak returns status 400. This typically happens when with a newly registered user and GitHub and OpenShift have not been linked yet.

The LoginService of fabric8-ui subscribes to this event and ultimately calls AuthenticationService.logout. The logout function clears the session data, which not only includes the auth token (if any), but also the refresh token.

The problem with all this is that the user has just logged in and landed on the getting started page. Since this was the first time logging in, keycloak generates a status 400. AuthenticationService publishes the event and LoginService wipes out the session while the user is on the getting started page.

As a result, the username is empty and there are no tokens. And because the session (refresh token) has been removed, the user cannot link neither the GitHub or OpenShift accounts.

That said, AuthenticationService broadcasts authenticationError in two places. That is, in createFederatedToken and inside refreshToken. I'm thinking we might not want to  broadcast authenticationError from createFederatedToken?

Or, perhaps broadcast a different event so LoginService understands how to handle each scenario?

**Comment by dlabrecq** [comment]
FYI, @jstrachan @pmuir

**Comment by dlabrecq** [comment]
FYI, @pmuir @joshuawilson

**Comment by dlabrecq** [comment]
This is reproducible on prod.

**Comment by pmuir** [comment]
We've seen 400s here from KC on regular usage (e.g. when your refresh token get's out of sync), so I'm not sure we should not handle this somehow. However I agree that we can't just send an authenticationError. Perhaps we can send a different event in this case (e.g. noFederatedToken) and then in fabric8-ui detect if they have, or have not, got past the _gettingStarted screen, and only do a logout if they have?

**Comment by dlabrecq** [comment]
Yes, a "noFederatedToken" event would work. I could then test if the user is on the getting started page, like you suggested.

**Comment by dlabrecq** [comment]
Fixed by:
https://github.com/fabric8-ui/ngx-login-client/pull/56
and
https://github.com/fabric8io/fabric8-ui/pull/1224
